<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Capturaimagen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get capturaimagen by id
     */
    function get_capturaimagen($id)
    {
        return $this->db->get_where('capturaimagen',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all capturaimagen
     */
    function get_all_capturaimagen()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('capturaimagen')->result_array();
    }
        
    /*
     * function to add new capturaimagen
     */
    function add_capturaimagen($params)
    {
        $this->db->insert('capturaimagen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update capturaimagen
     */
    function update_capturaimagen($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('capturaimagen',$params);
    }
    
    /*
     * function to delete capturaimagen
     */
    function delete_capturaimagen($id)
    {
        return $this->db->delete('capturaimagen',array('id'=>$id));
    }
}
