<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get configuracion by id
     */
    function get_configuracion($id)
    {
        return $this->db->get_where('configuracion',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all configuracion
     */
    function get_all_configuracion()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('configuracion')->result_array();
    }
        
    /*
     * function to add new configuracion
     */
    function add_configuracion($params)
    {
        $this->db->insert('configuracion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update configuracion
     */
    function update_configuracion($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('configuracion',$params);
    }
    
    /*
     * function to delete configuracion
     */
    function delete_configuracion($id)
    {
        return $this->db->delete('configuracion',array('id'=>$id));
    }
}
