<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notificacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notificacion by id
     */
    function get_notificacion($id)
    {
        return $this->db->get_where('notificacion',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all notificacion
     */
    function get_all_notificacion()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('notificacion')->result_array();
    }
        
    /*
     * function to add new notificacion
     */
    function add_notificacion($params)
    {
        $this->db->insert('notificacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notificacion
     */
    function update_notificacion($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('notificacion',$params);
    }
    
    /*
     * function to delete notificacion
     */
    function delete_notificacion($id)
    {
        return $this->db->delete('notificacion',array('id'=>$id));
    }
}
