<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Camara extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Camara_model');
    } 

    /*
     * Listing of camara
     */
    function index()
    {
        $data['camara'] = $this->Camara_model->get_all_camara();
        
        $data['_view'] = 'camara/index';
        $this->load->view('layouts/main',$data);
    }
     function indexV()
    {
        $data['camara'] = $this->Camara_model->get_all_camara();
        
        $data['_view'] = 'camara/indexV';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new camara
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'dirip' => $this->input->post('dirip'),
            );
            
            $camara_id = $this->Camara_model->add_camara($params);
            redirect('camara/index');
        }
        else
        {            
            $data['_view'] = 'camara/add';
            $this->load->view('layouts/main',$data);
        }
    }  
    function visualizarCamara1()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'dirip' => $this->input->post('dirip'),
            );
            
            $camara_id = $this->Camara_model->add_camara($params);
            redirect('camara/index');
        }
        else
        {            
            $data['_view'] = 'camara/visualizarCamara';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a camara
     */
    function edit($id)
    {   
        // check if the camara exists before trying to edit it
        $data['camara'] = $this->Camara_model->get_camara($id);
        
        if(isset($data['camara']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'dirip' => $this->input->post('dirip'),
                );

                $this->Camara_model->update_camara($id,$params);            
                redirect('camara/index');
            }
            else
            {
                $data['_view'] = 'camara/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The camara you are trying to edit does not exist.');
    } 
    function visualizarCamara($id)
    {   
        // check if the camara exists before trying to edit it
        $data['camara'] = $this->Camara_model->get_camara($id);
        
        if(isset($data['camara']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'dirip' => $this->input->post('dirip'),
                );

                $this->Camara_model->update_camara($id,$params);            
                redirect('camara/indexV');
            }
            else
            {
                $data['_view'] = 'camara/visualizarCamara';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The camara you are trying to edit does not exist.');
    } 

    /*
     * Deleting camara
     */
    function remove($id)
    {
        $camara = $this->Camara_model->get_camara($id);

        // check if the camara exists before trying to delete it
        if(isset($camara['id']))
        {
            $this->Camara_model->delete_camara($id);
            redirect('camara/index');
        }
        else
            show_error('The camara you are trying to delete does not exist.');
    }
    
}
