<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Capturaimagen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Capturaimagen_model');
    } 

    /*
     * Listing of capturaimagen
     */
    function index()
    {
        $data['capturaimagen'] = $this->Capturaimagen_model->get_all_capturaimagen();
        
        $data['_view'] = 'capturaimagen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new capturaimagen
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idcaptura' => $this->input->post('idcaptura'),
				'archivo' => $this->input->post('archivo'),
            );
            
            $capturaimagen_id = $this->Capturaimagen_model->add_capturaimagen($params);
            redirect('capturaimagen/index');
        }
        else
        {
			$this->load->model('Camara_model');
			$data['all_camara'] = $this->Camara_model->get_all_camara();
            
            $data['_view'] = 'capturaimagen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a capturaimagen
     */
    function edit($id)
    {   
        // check if the capturaimagen exists before trying to edit it
        $data['capturaimagen'] = $this->Capturaimagen_model->get_capturaimagen($id);
        
        if(isset($data['capturaimagen']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idcaptura' => $this->input->post('idcaptura'),
					'archivo' => $this->input->post('archivo'),
                );

                $this->Capturaimagen_model->update_capturaimagen($id,$params);            
                redirect('capturaimagen/index');
            }
            else
            {
				$this->load->model('Camara_model');
				$data['all_camara'] = $this->Camara_model->get_all_camara();

                $data['_view'] = 'capturaimagen/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The capturaimagen you are trying to edit does not exist.');
    } 

    /*
     * Deleting capturaimagen
     */
    function remove($id)
    {
        $capturaimagen = $this->Capturaimagen_model->get_capturaimagen($id);

        // check if the capturaimagen exists before trying to delete it
        if(isset($capturaimagen['id']))
        {
            $this->Capturaimagen_model->delete_capturaimagen($id);
            redirect('capturaimagen/index');
        }
        else
            show_error('The capturaimagen you are trying to delete does not exist.');
    }
    
}
