<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Configuracion_model');
    } 

    /*
     * Listing of configuracion
     */
    function index()
    {
        $data['configuracion'] = $this->Configuracion_model->get_all_configuracion();
        
        $data['_view'] = 'configuracion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new configuracion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tiempoGrabacion' => $this->input->post('tiempoGrabacion'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $configuracion_id = $this->Configuracion_model->add_configuracion($params);
            redirect('configuracion/index');
        }
        else
        {            
            $data['_view'] = 'configuracion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a configuracion
     */
    function edit($id)
    {   
        // check if the configuracion exists before trying to edit it
        $data['configuracion'] = $this->Configuracion_model->get_configuracion($id);
        
        if(isset($data['configuracion']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tiempoGrabacion' => $this->input->post('tiempoGrabacion'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Configuracion_model->update_configuracion($id,$params);            
                redirect('configuracion/index');
            }
            else
            {
                $data['_view'] = 'configuracion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The configuracion you are trying to edit does not exist.');
    } 

    /*
     * Deleting configuracion
     */
    function remove($id)
    {
        $configuracion = $this->Configuracion_model->get_configuracion($id);

        // check if the configuracion exists before trying to delete it
        if(isset($configuracion['id']))
        {
            $this->Configuracion_model->delete_configuracion($id);
            redirect('configuracion/index');
        }
        else
            show_error('The configuracion you are trying to delete does not exist.');
    }
    
}
