<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Evento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Evento_model');
    } 

    /*
     * Listing of evento
     */
    function index()
    {
        $data['evento'] = $this->Evento_model->get_all_evento();
        
        $data['_view'] = 'evento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new evento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idimagen' => $this->input->post('idimagen'),
				'fecha' => $this->input->post('fecha'),
				'tipodeteccion' => $this->input->post('tipodeteccion'),
            );
            
            $evento_id = $this->Evento_model->add_evento($params);
            redirect('evento/index');
        }
        else
        {
			$this->load->model('Capturaimagen_model');
			$data['all_capturaimagen'] = $this->Capturaimagen_model->get_all_capturaimagen();
            
            $data['_view'] = 'evento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a evento
     */
    function edit($id)
    {   
        // check if the evento exists before trying to edit it
        $data['evento'] = $this->Evento_model->get_evento($id);
        
        if(isset($data['evento']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idimagen' => $this->input->post('idimagen'),
					'fecha' => $this->input->post('fecha'),
					'tipodeteccion' => $this->input->post('tipodeteccion'),
                );

                $this->Evento_model->update_evento($id,$params);            
                redirect('evento/index');
            }
            else
            {
				$this->load->model('Capturaimagen_model');
				$data['all_capturaimagen'] = $this->Capturaimagen_model->get_all_capturaimagen();

                $data['_view'] = 'evento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The evento you are trying to edit does not exist.');
    } 

    /*
     * Deleting evento
     */
    function remove($id)
    {
        $evento = $this->Evento_model->get_evento($id);

        // check if the evento exists before trying to delete it
        if(isset($evento['id']))
        {
            $this->Evento_model->delete_evento($id);
            redirect('evento/index');
        }
        else
            show_error('The evento you are trying to delete does not exist.');
    }
    
}
